In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [11]:

 data =pd.read_csv('togo-dapaong_qc.csv')

In [12]:
data.head()

Timestamp  GHI  DNI  DHI  ModA  ModB  Tamb    RH   WS  WSgust  \
0  2021-10-25 00:01 -1.3  0.0  0.0   0.0   0.0  24.8  94.5  0.9     1.1   
1  2021-10-25 00:02 -1.3  0.0  0.0   0.0   0.0  24.8  94.4  1.1     1.6   
2  2021-10-25 00:03 -1.3  0.0  0.0   0.0   0.0  24.8  94.4  1.2     1.4   
3  2021-10-25 00:04 -1.2  0.0  0.0   0.0   0.0  24.8  94.3  1.2     1.6   
4  2021-10-25 00:05 -1.2  0.0  0.0   0.0   0.0  24.8  94.0  1.3     1.6   

   WSstdev     WD  WDstdev   BP  Cleaning  Precipitation  TModA  TModB  \
0      0.4  227.6      1.1  977         0            0.0   24.7   24.4   
1      0.4  229.3      0.7  977         0            0.0   24.7   24.4   
2      0.3  228.5      2.9  977         0            0.0   24.7   24.4   
3      0.3  229.1      4.6  977         0            0.0   24.7   24.4   
4      0.4  227.5      1.6  977         0            0.0   24.7   24.4   

   Comments  
0       NaN  
1       NaN  
2       NaN  
3       NaN  
4       NaN

In [13]:
data.shape

(525600, 19)

In [14]:
data.columns

Index(['Timestamp', 'GHI', 'DNI', 'DHI', 'ModA', 'ModB', 'Tamb', 'RH', 'WS',
       'WSgust', 'WSstdev', 'WD', 'WDstdev', 'BP', 'Cleaning', 'Precipitation',
       'TModA', 'TModB', 'Comments'],
      dtype='object')

In [15]:
data['DHI'].unique()

array([0.000e+00, 2.000e-01, 5.000e-01, ..., 6.362e+02, 6.644e+02,
       6.424e+02])

In [16]:
data['DNI'].unique()

array([  0. ,   4.2,   3. , ..., 342.9, 260. , 896.1])

In [17]:
data['ModA'].unique()

array([0.0000e+00, 1.0000e-01, 2.0000e-01, ..., 1.1712e+03, 1.0865e+03,
       1.0691e+03])

In [18]:
data.isnull()
data.isnull().sum()

Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64

In [26]:
import pandas as pd

data = pd.read_csv('togo-dapaong_qc.csv')

# Count occurrences of 0 in a specific column
  # Replace 'ColumnName' with the actual name of the column you want to check
zero_count = (data['DNI'] == 0).sum()

print(zero_count)

304763


In [27]:
import pandas as pd

data = pd.read_csv('togo-dapaong_qc.csv')

# Count occurrences of 0 in a specific column
  # Replace 'ColumnName' with the actual name of the column you want to check
zero_count = (data['DHI'] == 0).sum()

print(zero_count)

253015


In [28]:
import pandas as pd

data = pd.read_csv('togo-dapaong_qc.csv')

# Count occurrences of 0 in a specific column
  # Replace 'ColumnName' with the actual name of the column you want to check
zero_count = (data['GHI'] == 0).sum()

print(zero_count)

662


In [29]:
import pandas as pd

data = pd.read_csv('togo-dapaong_qc.csv')

# Count occurrences of 0 in a specific column
  # Replace 'ColumnName' with the actual name of the column you want to check
zero_count = (data['ModA'] == 0).sum()

print(zero_count)

246128


In [30]:
import pandas as pd

data = pd.read_csv('togo-dapaong_qc.csv')

# Count occurrences of 0 in a specific column
  # Replace 'ColumnName' with the actual name of the column you want to check
zero_count = (data['ModB'] == 0).sum()

print(zero_count)

246105


In [31]:
import pandas as pd

data = pd.read_csv('togo-dapaong_qc.csv')

# Count occurrences of 0 in a specific column
  # Replace 'ColumnName' with the actual name of the column you want to check
zero_count = (data['Cleaning'] == 0).sum()

print(zero_count)

525319


In [32]:
import pandas as pd

data = pd.read_csv('togo-dapaong_qc.csv')

# Count occurrences of 0 in a specific column
  # Replace 'ColumnName' with the actual name of the column you want to check
zero_count = (data['Precipitation'] == 0).sum()

print(zero_count)

522262


In [34]:
threshold = len(data) * 0.5
data_cleaned = data.dropna(axis=1, thresh=threshold)

In [41]:
data = data.drop(['Comments'], axis=1)
data.head()

Timestamp  Tamb    RH   WS  WSgust  WSstdev     WD  WDstdev   BP  \
0  2021-10-25 00:01  24.8  94.5  0.9     1.1      0.4  227.6      1.1  977   
1  2021-10-25 00:02  24.8  94.4  1.1     1.6      0.4  229.3      0.7  977   
2  2021-10-25 00:03  24.8  94.4  1.2     1.4      0.3  228.5      2.9  977   
3  2021-10-25 00:04  24.8  94.3  1.2     1.6      0.3  229.1      4.6  977   
4  2021-10-25 00:05  24.8  94.0  1.3     1.6      0.4  227.5      1.6  977   

   TModA  TModB  
0   24.7   24.4  
1   24.7   24.4  
2   24.7   24.4  
3   24.7   24.4  
4   24.7   24.4